WcaOnRails/config/routes.rb
    get 'register' => 'registrations#register'
    get 'payment-success' => 'registrations#payment_success'
    get 'register-require-sign-in' => 'registrations#register_require_sign_in'
    resources :competition_tabs, except: [:show], as: :tabs, path: :tabs
    get 'tabs/:id/reorder' => "competition_tabs#reorder", as: :tab_reorder
    # Delegate views and action
    get 'submit-results' => 'results_submission#new', as: :submit_results_edit
    post 'submit-results' => 'results_submission#create', as: :submit_results
    post 'upload-json' => 'results_submission#upload_json', as: :upload_results_json
    # WRT views and action
    get '/admin/upload-results' => "admin#new_results", as: :admin_upload_results_edit
    get '/admin/check-existing-results' => "admin#check_results", as: :admin_check_existing_results
    post '/admin/upload-json' => "admin#create_results", as: :admin_upload_results
    post '/admin/clear-submission' => "admin#clear_results_submission", as: :clear_results_submission
  end
  post 'admin/check-existing-results' => "admin#run_validators", as: :admin_run_validators

  get 'competitions/:competition_id/report/edit' => 'delegate_reports#edit', as: :delegate_report_edit
  get 'competitions/:competition_id/report' => 'delegate_reports#show', as: :delegate_report
  patch 'competitions/:competition_id/report' => 'delegate_reports#update'

  get 'competitions/:id/edit/admin' => 'competitions#admin_edit', as: :admin_edit_competition
  get 'competitions/:id/payment_setup' => 'competitions#payment_setup', as: :competitions_payment_setup
  get 'stripe-connect' => 'competitions#stripe_connect', as: :competitions_stripe_connect
  get 'competitions/:id/events/edit' => 'competitions#edit_events', as: :edit_events
  get 'competitions/:id/schedule/edit' => 'competitions#edit_schedule', as: :edit_schedule
  get 'competitions/edit/nearby_competitions' => 'competitions#nearby_competitions', as: :nearby_competitions
  get 'competitions/edit/time_until_competition' => 'competitions#time_until_competition', as: :time_until_competition
  get 'competitions/:id/edit/clone_competition' => 'competitions#clone_competition', as: :clone_competition
  get 'competitions/edit/currency_convert' => 'competitions#currency_convert', as: :currency_convert

  get 'results/rankings', to: redirect('results/rankings/333/single', status: 302)
  get 'results/rankings/333mbf/average',
      to: redirect(status: 302) { |params, request| URI.parse(request.original_url).query ? "results/rankings/333mbf/single?#{URI.parse(request.original_url).query}" : "results/rankings/333mbf/single" }
  get 'results/rankings/:event_id', to: redirect('results/rankings/%{event_id}/single', status: 302)
  get 'results/rankings/:event_id/:type' => 'results#rankings', as: :rankings
  get 'results/records' => 'results#records', as: :records

  get "media/validate" => 'media#validate', as: :validate_media
  resources :media, only: [:index, :new, :create, :edit, :update, :destroy]

  resources :persons, only: [:index, :show]

  resources :polls, only: [:edit, :new, :vote, :create, :update, :index, :destroy]
  get 'polls/:id/vote' => 'votes#vote', as: 'polls_vote'
  get 'polls/:id/results' => 'polls#results', as: 'polls_results'

  resources :teams, only: [:index, :update, :edit]

  resources :votes, only: [:create, :update]

  post 'competitions/:id/post_announcement' => 'competitions#post_announcement', as: :competition_post_announcement
  post 'competitions/:id/cancel' => 'competitions#cancel_competition', as: :competition_cancel
  post 'competitions/:id/post_results' => 'competitions#post_results', as: :competition_post_results

  get 'panel' => 'panel#index'
  get 'panel/delegate-crash-course', to: redirect('/edudoc/delegate-crash-course/delegate_crash_course.pdf', status: 302)
  patch 'panel/delegate-crash-course' => 'panel#update_delegate_crash_course'
  get 'panel/pending-claims(/:user_id)' => 'panel#pending_claims_for_subordinate_delegates', as: 'pending_claims'
  get 'panel/seniors' => 'panel#seniors'
  resources :notifications, only: [:index]

  root 'posts#homepage'
  resources :posts
  get 'rss' => 'posts#rss'

  post 'upload/image', to: 'upload#image'

  get 'admin/delegates' => 'delegates#stats', as: :delegates_stats

  get 'robots' => 'static_pages#robots'

  get 'server-status' => 'server_status#index'

  get 'translations', to: redirect('translations/status', status: 302)
  get 'translations/status' => 'translations#index'
  get 'translations/edit' => 'translations#edit'
  patch 'translations/update' => 'translations#update'

  get 'about' => 'static_pages#about'
  get 'teams-committees' => 'static_pages#teams_committees'
  get 'documents' => 'static_pages#documents'
  get 'education' => 'static_pages#education'
  get 'delegates' => 'static_pages#delegates'
  get 'disclaimer' => 'static_pages#disclaimer'
  get 'contact' => 'static_pages#contact'
  get 'speedcubing-history' => 'static_pages#speedcubing_history'
  get 'privacy' => 'static_pages#privacy'
  get 'faq' => 'static_pages#faq'
  get 'score-tools' => 'static_pages#score_tools'
  get 'logo' => 'static_pages#logo'
  get 'media-instagram' => 'static_pages#media_instagram'
  get 'wca-workbook-assistant' => 'static_pages#wca_workbook_assistant'
  get 'wca-workbook-assistant-versions' => 'static_pages#wca_workbook_assistant_versions'
  get 'organizer-guidelines' => 'static_pages#organizer_guidelines'
  get 'tutorial' => redirect('/education', status: 302)

  resources :regional_organizations, only: [:new, :update, :edit, :destroy], path: '/regional-organizations'
  get 'organizations' => 'regional_organizations#index'
  get 'admin/regional-organizations' => 'regional_organizations#admin'
  delete 'admin/regional-organizations' => 'regional_organizations#destroy'
  patch 'regional-organizations/:id/edit' => 'regional_organizations#update'
  post 'regional-organizations/new' => 'regional_organizations#create'

  get 'disciplinary' => 'wdc#root'

  get 'contact/website' => 'contacts#website'
  post 'contact/website' => 'contacts#website_create'
  get 'contact/dob' => 'contacts#dob'
  post 'contact/dob' => 'contacts#dob_create'

  get '/regulations' => 'regulations#show', id: 'index'
  get '/regulations/*id' => 'regulations#show'

  get '/admin' => 'admin#index'
  get '/admin/all-voters' => 'admin#all_voters', as: :eligible_voters
  get '/admin/leader-senior-voters' => 'admin#leader_senior_voters', as: :leader_senior_voters
  get '/admin/merge_people' => 'admin#merge_people'
  post '/admin/merge_people' => 'admin#do_merge_people'
  get '/admin/edit_person' => 'admin#edit_person'
  patch '/admin/update_person' => 'admin#update_person'
  get '/admin/person_data' => 'admin#person_data'
  get '/admin/compute_auxiliary_data' => 'admin#compute_auxiliary_data'
  get '/admin/do_compute_auxiliary_data' => 'admin#do_compute_auxiliary_data'
  get '/admin/update_statistics' => 'admin#update_statistics'
  get '/admin/anonymize_person' => 'admin#anonymize_person'
  post '/admin/anonymize_person' => 'admin#do_anonymize_person'
  get '/admin/reassign_wca_id' => 'admin#reassign_wca_id'
  get '/admin/validate_reassign_wca_id' => 'admin#validate_reassign_wca_id'
  post '/admin/reassign_wca_id' => 'admin#do_reassign_wca_id'

  get '/search' => 'search_results#index'

  post '/render_markdown' => 'markdown_renderer#render_markdown'

  patch '/update_locale/:locale' => 'application#update_locale', as: :update_locale

  get '/relations' => 'relations#index'
  get '/relation' => 'relations#relation'

  get '/.well-known/change-password' => redirect('/profile/edit?section=password', status: 302)

  # WFC section
  get '/wfc' => 'wfc#panel'
  scope 'wfc' do
    get '/competitions_export' => 'wfc#competition_export', defaults: { format: :csv }, as: :wfc_competitions_export
    resources :country_bands, only: [:index, :update, :edit], path: '/country-bands'
  end

  scope :archive do
    # NOTE: This is meant for displaying old content of the phpBB forum. It is DEPRECATED!
    resources :forums, only: [:index, :show]
    resources :forum_topics, only: [:show]
  end

  resources :incidents do
    patch '/mark_as/:kind' => 'incidents#mark_as', as: :mark_as
  end

  get '/sso-discourse' => 'users#sso_discourse'

  namespace :api do
    get '/', to: redirect('/api/v0', status: 302)
    namespace :v0 do
      get '/' => 'api#help'
      get '/me' => 'api#me'
      get '/auth/results' => 'api#auth_results'
      get '/export/public' => 'api#export_public'
      get '/scramble-program' => 'api#scramble_program'
      get '/search' => 'api#omni_search'
      get '/search/posts' => 'api#posts_search'
      get '/search/competitions' => 'api#competitions_search'
      get '/search/users' => 'api#users_search'
      get '/search/regulations' => 'api#regulations_search'
      get '/users/:id' => 'api#show_user_by_id', constraints: { id: /\d+/ }
      get '/users/:wca_id' => 'api#show_user_by_wca_id'
      get '/delegates' => 'api#delegates'
      get '/persons' => "persons#index"
      get '/persons/:wca_id' => "persons#show", as: :person
      get '/persons/:wca_id/results' => "persons#results", as: :person_results
      get '/geocoding/search' => 'geocoding#get_location_from_query'
      resources :competitions, only: [:index, :show] do
        get '/wcif' => 'competitions#show_wcif'
        get '/wcif/public' => 'competitions#show_wcif_public'
        get '/results' => 'competitions#results', as: :results
        get '/results/:event_id' => 'competitions#event_results', as: :event_results
        get '/competitors' => 'competitions#competitors'
        get '/registrations' => 'competitions#registrations'
        get '/schedule' => 'competitions#schedule'
        get '/scrambles' => 'competitions#scrambles', as: :scrambles
        get '/scrambles/:event_id' => 'competitions#event_scrambles', as: :event_scrambles
        patch '/wcif' => 'competitions#update_wcif', as: :update_wcif
      end
      get '/records' => "api#records"

WcaOnRails/app/controllers/panel_controller.rb
# frozen_string_literal: true

class PanelController < ApplicationController
  include DocumentsHelper

  before_action :authenticate_user!
  before_action -> { redirect_to_root_unless_user(:staff?) }
  before_action -> { redirect_to_root_unless_user(:can_view_senior_delegate_material?) }, only: [:pending_claims_for_subordinate_delegates]
  before_action -> { redirect_to_root_unless_user(:board_member?) }, only: [:seniors]

  def index
  end

  def pending_claims_for_subordinate_delegates
    # Show pending claims for a given user, or the current user, if they can see them
    @user = User.includes(subordinate_delegates: [:confirmed_users_claiming_wca_id]).find_by_id!(params[:user_id] || current_user.id)
    @subordinate_delegates = @user.subordinate_delegates.to_a.push(@user)
  end

  def seniors
    # Show the list of seniors and actions available
    @seniors = User.senior_delegates.order(:name)
  end

  private def editable_post_fields
    [:body]
  end
  helper_method :editable_post_fields

  private def post_params
    params.require(:post).permit(*editable_post_fields)
  end
end

WcaOnRails/app/views/panel/index.html.erb
<% provide(:title, 'Panel') %>

<div class="container">
  <h1><%= yield(:title) %></h1>

  <h2>Staff</h2>

  <ul>
    <%= documents_list("policies/internal") %>
    <li>
      <%= link_to("Staff crash course", "/edudoc/staff-crash-course/staff_crash_course.pdf") %>
    </li>
  </ul>

  <% if current_user&.can_view_delegate_matters? %>
    <h2>Delegates</h2>

    <ul>
      <li>
        <%= link_to "Delegate Crash course", panel_delegate_crash_course_path %>
      </li>
      <li>
        <%= link_to "Delegates", delegates_stats_path %>
      </li>
      <li>
        <%= link_to "WR Submission Form", "https://docs.google.com/forms/d/e/1FAIpQLSeJwf6b7yGGyWFhU0xfKSF3ki_nITyIKXVFRP86unb9EYRtHQ/viewform" %>
      </li>
      <li>
        <%= link_to "Gear Order Form", "https://docs.google.com/forms/d/e/1FAIpQLSfyOMy9TtOIeIz7N8_4hPXNA6ScKVIzi11BmLWVx0-ovQnsWQ/viewform?usp=sf_link" %>
      </li>
      <li>
        <%= link_to "Travel Reimbursement Form", "https://docs.google.com/forms/d/12tz2I_EeBORm14kQO6ZB5TOp321YbXkIXvrxUNIHxN0/viewform" %>
      </li>
      <li>
        <%= link_to "Equipment Funding Form", "https://docs.google.com/forms/d/e/1FAIpQLSeglibvXYG6Z2CzIPbxu2LTpAuXkJPK-vi4GuOnBFx1756ufA/viewform" %>
      </li>
    </ul>
  <% end %>

  <% if current_user&.can_view_senior_delegate_material? %>
    <h2>Senior Delegates</h2>

    <ul>
      <li>
        <%= link_to "WCA Delegate Nomination form", "https://docs.google.com/forms/d/e/1FAIpQLSfji_fOKEKcqS1Fb9fpu3qsBx-O8LiSJu_fG0TU7DJnR9Yj8g/viewform" %>
      </li>
      <li>
        <%= link_to "WCA Delegate Promotion form", "https://docs.google.com/forms/d/e/1FAIpQLScq0JIOq1-2PHJoty5IE_uln_1Uq26Isp4mr3bqpfXKELQoqQ/viewform" %>
      </li>
      <li>
        <%= link_to "WCA Delegate Demotion form", "https://docs.google.com/forms/d/e/1FAIpQLSf5BnccDL656ZPD3zl72Xgz7LmzLjFeTtjXKqvupo9Tn_VIRg/viewform" %>
      </li>
      <li>
        <%= link_to "Pending claims for your subordinate Delegates", pending_claims_path %>
      </li>
      <li>
        <%= link_to "Upcoming competitions for your subordinate Delegates", competitions_for_senior_path %>
      </li>
      <li>
        <%= link_to "Modify Delegates on Probation", edit_team_path(Team.probation) %>
      </li>
    </ul>
  <% end %>


  <% if current_user.can_admin_finances? %>
    <h2><%= Team.wfc.name %></h2>

    <ul>
      <li>
        <%= link_to "WFC panel", wfc_path %>
      </li>
      <li>
        <%= link_to "Modify Delegates on Probation", edit_team_path(Team.probation) %>
      </li>
    </ul>
  <% end %>


  <% if current_user&.can_view_leader_material? %>
    <h2>Committee/Team Leaders</h2>

    <ul>
      <li>
        <%= link_to "WCA Committee/Team Member Promotion form", "https://docs.google.com/forms/d/e/1FAIpQLSf3079GXcGUYDmJIIdRt0GPlDA_-aMSBZqk93zDgaFRxG15xQ/viewform" %>
      </li>
    </ul>
  <% end %>

  <% if current_user&.board_member? %>
    <h2>Board</h2>

    <ul>
      <li>
        <%= link_to "List of Senior Delegates", panel_seniors_path %>
      </li>
    </ul>
  <% end %>
</div>

WcaOnRails/app/views/panel/pending_claims_for_subordinate_delegates.html.erb
<% provide(:title, 'Pending claims for subordinate Delegates') %>

<div class="container">
  <h2>Pending WCA ID claims for Delegates managed by <%= @user.name %></h2>

  <div class="panel-group">
    <% @subordinate_delegates.sort_by { |u| u.confirmed_users_claiming_wca_id.size }.reverse_each do |delegate| %>
      <% users = delegate.confirmed_users_claiming_wca_id %>
      <div class="panel panel-default">
        <div class="panel-heading heading-as-link" data-toggle="collapse" data-target="#panel-<%= delegate.id %>">
          <%= delegate.name %>
          <span class="badge"><%= users.size %></span>
        </div>
        <div id="panel-<%= delegate.id %>" class="collapse panel-collapse">
          <ul class="list-group">
            <% if users.empty? %>
              <li class="list-group-item">No pending claims.</li>
            <% else %>
              <% users.each do |u| %>
                <%= link_to(edit_user_path(u.id, anchor: "wca_id"), class: "list-group-item") do %>
                  <%= u.name %> has claimed WCA ID <%= u.unconfirmed_wca_id %>
                <% end %>
              <% end %>
            <% end %>
          </ul>
        </div>
      </div>
    <% end %>
  </div>
</div>

WcaOnRails/app/views/panel/seniors.html.erb
<% provide(:title, 'List of Senior Delegates') %>

<div class="container">
  <h2>List of Senior Delegates</h2>
  <p>Below is the list of all Senior Delegates and the actions available for them:</p>
  <% @seniors.each do |s| %>
    <h4><%= s.name %></h4>
    <ul>
      <li><%= link_to("List of subordinate pending WCA ID claims", pending_claims_path(s.id)) %></li>
      <li><%= link_to("List of subordinate upcoming competitions", competitions_for_senior_path(s.id)) %></li>
    </ul>
  <% end %>
</div>