WcaOnRails/config/routes.rb
    get 'registrations/add' => 'registrations#add', as: :registrations_add
    post 'registrations/add' => 'registrations#do_add', as: :registrations_do_add
    get 'registrations/psych-sheet' => 'registrations#psych_sheet', as: :psych_sheet
    get 'registrations/psych-sheet/:event_id' => 'registrations#psych_sheet_event', as: :psych_sheet_event
    resources :registrations, only: [:index, :update, :create, :edit, :destroy], shallow: true
    get 'edit/registrations' => 'registrations#edit_registrations'
    get 'register' => 'registrations#register'
    get 'payment-success' => 'registrations#payment_success'
    get 'register-require-sign-in' => 'registrations#register_require_sign_in'
    resources :competition_tabs, except: [:show], as: :tabs, path: :tabs
    get 'tabs/:id/reorder' => "competition_tabs#reorder", as: :tab_reorder
    # Delegate views and action
    get 'submit-results' => 'results_submission#new', as: :submit_results_edit
    post 'submit-results' => 'results_submission#create', as: :submit_results
    post 'upload-json' => 'results_submission#upload_json', as: :upload_results_json
    # WRT views and action
    get '/admin/upload-results' => "admin#new_results", as: :admin_upload_results_edit
    get '/admin/check-existing-results' => "admin#check_results", as: :admin_check_existing_results
    post '/admin/upload-json' => "admin#create_results", as: :admin_upload_results
    post '/admin/clear-submission' => "admin#clear_results_submission", as: :clear_results_submission
  end
  post 'admin/check-existing-results' => "admin#run_validators", as: :admin_run_validators

  get 'competitions/:competition_id/report/edit' => 'delegate_reports#edit', as: :delegate_report_edit
  get 'competitions/:competition_id/report' => 'delegate_reports#show', as: :delegate_report
  patch 'competitions/:competition_id/report' => 'delegate_reports#update'

  get 'competitions/:id/edit/admin' => 'competitions#admin_edit', as: :admin_edit_competition
  get 'competitions/:id/payment_setup' => 'competitions#payment_setup', as: :competitions_payment_setup
  get 'stripe-connect' => 'competitions#stripe_connect', as: :competitions_stripe_connect
  get 'competitions/:id/events/edit' => 'competitions#edit_events', as: :edit_events
  get 'competitions/:id/schedule/edit' => 'competitions#edit_schedule', as: :edit_schedule
  get 'competitions/edit/nearby_competitions' => 'competitions#nearby_competitions', as: :nearby_competitions
  get 'competitions/edit/time_until_competition' => 'competitions#time_until_competition', as: :time_until_competition
  get 'competitions/:id/edit/clone_competition' => 'competitions#clone_competition', as: :clone_competition
  get 'competitions/edit/currency_convert' => 'competitions#currency_convert', as: :currency_convert

  get 'results/rankings', to: redirect('results/rankings/333/single', status: 302)
  get 'results/rankings/333mbf/average',
      to: redirect(status: 302) { |params, request| URI.parse(request.original_url).query ? "results/rankings/333mbf/single?#{URI.parse(request.original_url).query}" : "results/rankings/333mbf/single" }
  get 'results/rankings/:event_id', to: redirect('results/rankings/%{event_id}/single', status: 302)
  get 'results/rankings/:event_id/:type' => 'results#rankings', as: :rankings
  get 'results/records' => 'results#records', as: :records

  get "media/validate" => 'media#validate', as: :validate_media
  resources :media, only: [:index, :new, :create, :edit, :update, :destroy]

  resources :persons, only: [:index, :show]

  resources :polls, only: [:edit, :new, :vote, :create, :update, :index, :destroy]
  get 'polls/:id/vote' => 'votes#vote', as: 'polls_vote'
  get 'polls/:id/results' => 'polls#results', as: 'polls_results'

  resources :teams, only: [:index, :update, :edit]

  resources :votes, only: [:create, :update]

  post 'competitions/:id/post_announcement' => 'competitions#post_announcement', as: :competition_post_announcement
  post 'competitions/:id/cancel' => 'competitions#cancel_competition', as: :competition_cancel
  post 'competitions/:id/post_results' => 'competitions#post_results', as: :competition_post_results

  get 'panel' => 'panel#index'
  get 'panel/delegate-crash-course', to: redirect('/edudoc/delegate-crash-course/delegate_crash_course.pdf', status: 302)
  patch 'panel/delegate-crash-course' => 'panel#update_delegate_crash_course'
  get 'panel/pending-claims(/:user_id)' => 'panel#pending_claims_for_subordinate_delegates', as: 'pending_claims'
  get 'panel/seniors' => 'panel#seniors'
  resources :notifications, only: [:index]

  root 'posts#homepage'
  resources :posts
  get 'rss' => 'posts#rss'

  post 'upload/image', to: 'upload#image'

  get 'admin/delegates' => 'delegates#stats', as: :delegates_stats

  get 'robots' => 'static_pages#robots'

  get 'server-status' => 'server_status#index'

  get 'translations', to: redirect('translations/status', status: 302)
  get 'translations/status' => 'translations#index'
  get 'translations/edit' => 'translations#edit'
  patch 'translations/update' => 'translations#update'

  get 'about' => 'static_pages#about'
  get 'teams-committees' => 'static_pages#teams_committees'
  get 'documents' => 'static_pages#documents'
  get 'education' => 'static_pages#education'
  get 'delegates' => 'static_pages#delegates'
  get 'disclaimer' => 'static_pages#disclaimer'
  get 'contact' => 'static_pages#contact'
  get 'speedcubing-history' => 'static_pages#speedcubing_history'
  get 'privacy' => 'static_pages#privacy'
  get 'faq' => 'static_pages#faq'
  get 'score-tools' => 'static_pages#score_tools'
  get 'logo' => 'static_pages#logo'
  get 'media-instagram' => 'static_pages#media_instagram'
  get 'wca-workbook-assistant' => 'static_pages#wca_workbook_assistant'
  get 'wca-workbook-assistant-versions' => 'static_pages#wca_workbook_assistant_versions'
  get 'organizer-guidelines' => 'static_pages#organizer_guidelines'
  get 'tutorial' => redirect('/education', status: 302)

  resources :regional_organizations, only: [:new, :update, :edit, :destroy], path: '/regional-organizations'
  get 'organizations' => 'regional_organizations#index'
  get 'admin/regional-organizations' => 'regional_organizations#admin'
  delete 'admin/regional-organizations' => 'regional_organizations#destroy'
  patch 'regional-organizations/:id/edit' => 'regional_organizations#update'
  post 'regional-organizations/new' => 'regional_organizations#create'

  get 'disciplinary' => 'wdc#root'

  get 'contact/website' => 'contacts#website'
  post 'contact/website' => 'contacts#website_create'
  get 'contact/dob' => 'contacts#dob'
  post 'contact/dob' => 'contacts#dob_create'

  get '/regulations' => 'regulations#show', id: 'index'
  get '/regulations/*id' => 'regulations#show'

  get '/admin' => 'admin#index'
  get '/admin/all-voters' => 'admin#all_voters', as: :eligible_voters
  get '/admin/leader-senior-voters' => 'admin#leader_senior_voters', as: :leader_senior_voters
  get '/admin/merge_people' => 'admin#merge_people'
  post '/admin/merge_people' => 'admin#do_merge_people'
  get '/admin/edit_person' => 'admin#edit_person'
  patch '/admin/update_person' => 'admin#update_person'
  get '/admin/person_data' => 'admin#person_data'
  get '/admin/compute_auxiliary_data' => 'admin#compute_auxiliary_data'
  get '/admin/do_compute_auxiliary_data' => 'admin#do_compute_auxiliary_data'
  get '/admin/update_statistics' => 'admin#update_statistics'
  get '/admin/anonymize_person' => 'admin#anonymize_person'
  post '/admin/anonymize_person' => 'admin#do_anonymize_person'
  get '/admin/reassign_wca_id' => 'admin#reassign_wca_id'
  get '/admin/validate_reassign_wca_id' => 'admin#validate_reassign_wca_id'
  post '/admin/reassign_wca_id' => 'admin#do_reassign_wca_id'

  get '/search' => 'search_results#index'

  post '/render_markdown' => 'markdown_renderer#render_markdown'

  patch '/update_locale/:locale' => 'application#update_locale', as: :update_locale

  get '/relations' => 'relations#index'
  get '/relation' => 'relations#relation'

  get '/.well-known/change-password' => redirect('/profile/edit?section=password', status: 302)

  # WFC section
  get '/wfc' => 'wfc#panel'
  scope 'wfc' do
    get '/competitions_export' => 'wfc#competition_export', defaults: { format: :csv }, as: :wfc_competitions_export
    resources :country_bands, only: [:index, :update, :edit], path: '/country-bands'
  end

  scope :archive do
    # NOTE: This is meant for displaying old content of the phpBB forum. It is DEPRECATED!
    resources :forums, only: [:index, :show]
    resources :forum_topics, only: [:show]
  end

  resources :incidents do
    patch '/mark_as/:kind' => 'incidents#mark_as', as: :mark_as
  end

  get '/sso-discourse' => 'users#sso_discourse'

  namespace :api do
    get '/', to: redirect('/api/v0', status: 302)
    namespace :v0 do
      get '/' => 'api#help'
      get '/me' => 'api#me'
      get '/auth/results' => 'api#auth_results'
      get '/export/public' => 'api#export_public'
      get '/scramble-program' => 'api#scramble_program'
      get '/search' => 'api#omni_search'
      get '/search/posts' => 'api#posts_search'
      get '/search/competitions' => 'api#competitions_search'
      get '/search/users' => 'api#users_search'
      get '/search/regulations' => 'api#regulations_search'
      get '/users/:id' => 'api#show_user_by_id', constraints: { id: /\d+/ }
      get '/users/:wca_id' => 'api#show_user_by_wca_id'
      get '/delegates' => 'api#delegates'
      get '/persons' => "persons#index"
      get '/persons/:wca_id' => "persons#show", as: :person
      get '/persons/:wca_id/results' => "persons#results", as: :person_results
      get '/geocoding/search' => 'geocoding#get_location_from_query'
      resources :competitions, only: [:index, :show] do
        get '/wcif' => 'competitions#show_wcif'
        get '/wcif/public' => 'competitions#show_wcif_public'
        get '/results' => 'competitions#results', as: :results

WcaOnRails/app/controllers/media_controller.rb
# frozen_string_literal: true

class MediaController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action -> { redirect_to_root_unless_user(:can_approve_media?) }, except: [:index, :new, :create]

  def new
    @medium = CompetitionMedium.new
  end

  def create
    params = medium_params.merge(
      "status" => "pending",
      "submitterName" => current_user.name,
      "submitterEmail" => current_user.email,
    )
    @medium = CompetitionMedium.new(params)

    if @medium.save
      flash[:success] = "Thanks for sending us new media!"
      redirect_to new_medium_path
    else
      render :new
    end
  end

  private def get_media
    params[:year] ||= "all years"
    params[:region] ||= "all"

    media = CompetitionMedium.includes(:competition).where(status: params[:status]).order(timestampSubmitted: :desc)
    media = media.where("Competitions.year": params[:year]) unless params[:year] == "all years"
    media = media.belongs_to_region(params[:region]) unless params[:region] == "all"

    media
  end

  def index
    params[:status] = "accepted"
    params[:year] ||= Date.today.year
    @media = get_media
    render :index
  end

  def validate
    params[:status] ||= "pending"
    @media = get_media
    I18n.with_locale(:en) { render :validate }
  end

  def edit
    @medium = find_medium
    I18n.with_locale(:en) { render :edit }
  end

  def update
    @medium = find_medium
    if @medium.update(medium_params)
      flash[:success] = "Updated medium"
      redirect_to edit_medium_path(@medium)
    else
      I18n.with_locale(:en) { render :edit }
    end
  end

  def destroy
    @medium = find_medium
    if @medium.destroy
      flash[:success] = "Deleted medium"
      redirect_to validate_media_path
    else
      I18n.with_locale(:en) { render :edit }
    end
  end

  private def medium_params
    params.require(:competition_medium).permit(
      :competitionId,
      :type,
      :text,
      :uri,
      :submitterName,
      :submitterEmail,
      :submitterComment,
      :status,
    )
  end

  private def find_medium
    CompetitionMedium.find(params[:id])
  end
end

WcaOnRails/app/views/media/_approval_guidelines.html.erb
<div class="well">
  <h3>Checklist before approving media</h3>
  <ul>
    <li>All media content must be related to the selected competition.</li>
    <li>All media content must be appropriate and clean and not contain any improper or offensive material.</li>
    <li>If the media content is huge, the checking can be done on excerpts only.</li>
    <li>If there is presence of sponsors / ads, it must be moderate.</li>
    <li>All media content should have appropriate and descriptive titles. If only this condition is not met, a results team members can choose to set an appropriate and descriptive title before approving the content.</li>
  </ul>
</div>

WcaOnRails/app/views/media/_media_table.html.erb
<% show_edit_buttons = defined?(show_edit_buttons) && show_edit_buttons %>

<script>
  function sortBySorter(a, b) {
    return b['sort-by'] - a['sort-by'];
  }
</script>

<form action="" method="get" class="form-inline">
  <div class="form-group">
    <label for="year-selector"><%= t '.year' %></label>
    <%= select_tag "year",
                   year_option_tags(selected_year: params[:year], exclude_future: true),
                   id: "year-selector",
                   class: "form-control"
    %>
  </div>

  <div class="form-group">
    <%= label_tag(t('competitions.index.region')) %>
    <%= select_tag(:region, region_option_tags(selected_id: params[:region]), class: "form-control") %>
  </div>

  <% if show_edit_buttons %>
    <div class="form-group">
      <label for="status-selector"><%= t 'activerecord.attributes.competition_medium.status' %></label>
      <%= select_tag "status",
                     options_for_select(CompetitionMedium.statuses_i18n.invert, params[:status]),
                     id: "status-selector",
                     class: "form-control"
      %>
    </div>
  <% end %>

  <input type="submit" class="btn btn-default" value="<%= t 'common.filter' %>" />
</form>

<%= wca_table table_class: "media", data: { toggle: "table", sort_name: "submission-date", sort_order: "desc" } do %>
  <thead>
    <tr>
      <th data-sortable="true" data-field="submission-date" data-sort-name="_submission-date_data" data-sorter="sortBySorter">Submission Date</th>
      <th data-sortable="true" data-field="competition-date" data-sort-name="_competition-date_data" data-sorter="sortBySorter">Competition Date</th>
      <th><%= t 'activerecord.attributes.competition_medium.competitionId' %></th>
      <th><%= t '.location' %></th>
      <th><%= t 'activerecord.attributes.competition_medium.type' %></th>
      <th><%= t 'activerecord.attributes.competition_medium.uri' %></th>
      <% if show_edit_buttons %>
        <th></th>
      <% end %>

      <!-- Extra column for .table-greedy-last-column -->
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% media.each do |medium| %>
      <% competition = medium.competition %>
      <tr data-medium-id="<%= medium.id %>">
        <td data-sort-by="<%= medium.timestampSubmitted.to_i %>"><%= medium.timestampSubmitted.to_formatted_s(:long_utc) %></td>
        <td data-sort-by="<%= competition.start_date.to_time.to_i %>">
          <%= wca_date_range(competition.start_date, competition.end_date) %>
        </td>
        <td><%= link_to competition.name, competition_path(competition) %></td>
        <td><strong><%= competition.country.name %></strong>, <%= competition.cityName %></td>
        <td><%= medium.type %></td>
        <td><%= link_to medium.text, medium.uri %></td>
        <% if show_edit_buttons %>
          <td>
            <% if medium.pending? %>
              <%= button_to medium_path(medium),
                            title: t('.accept'),
                            class: "btn btn-link",
                            method: :patch,
                            params: { "competition_medium[status]" => "accepted" },
                            data: { confirm: t('.confirm_accept') } do
              %>
                <%= ui_icon("check") %>
              <% end %>
            <% end %>
            <%= link_to ui_icon("pencil alt"), edit_medium_path(medium), title: t('.edit') %>
            <%= button_to medium_path(medium),
                          title: t('common.delete'),
                          class: "btn btn-link",
                          method: :delete,
                          data: { confirm: t('media.common.confirm_delete') } do
            %>
              <%= ui_icon("trash") %>
            <% end %>
          </td>
        <% end %>

        <!-- Extra column for .table-greedy-last-column -->
        <td></td>
    <% end %>
  </tbody>
<% end %>

WcaOnRails/app/views/media/edit.html.erb
<% provide(:title, t('.title')) %>

<div class="container">
  <%= link_to t('.validate_media_page'), validate_media_path %>

  <h2><%= yield(:title) %></h2>

  <%= render "approval_guidelines" %>

  <%= horizontal_simple_form_for @medium, url: medium_path(@medium), html: { class: 'are-you-sure' } do |f| %>
    <%= f.input :competitionId, as: :competition_id, only_one: true %>
    <%= f.input :type, include_blank: false %>
    <%= f.input :text %>
    <%= f.input :uri %>
    <%= f.input :submitterName %>
    <%= f.input :submitterEmail %>
    <%= f.input :submitterComment %>
    <%= f.input :status, include_blank: false %>

    <%= f.button :submit %>
    <%= link_to medium_path(@medium),
                method: :delete,
                class: "btn btn-danger",
                data: { confirm: t('media.common.confirm_delete') } do %>
      <%= ui_icon("trash") %> <%= t('common.delete') %>
    <% end %>
  <% end %>
</div>

WcaOnRails/app/views/media/index.html.erb
<% provide(:title, t('.title')) %>

<div class="container-fluid">
  <h2>
    <%= yield(:title) %>
    <% if current_user&.can_approve_media? %>
      <%= link_to validate_media_path, title: t('.validate_media') do %>
        <span class="badge"><%= CompetitionMedium.pending.count %></span>
      <% end %>
    <% end %>
  </h2>

  <%= t('.submit_media_html') %>
  <hr>

  <%= render "media_table", media: @media %>
</div>

WcaOnRails/app/views/media/new.html.erb
<% provide(:title, t('.title')) %>

<div class="container">
  <h2><%= yield(:title) %></h2>

  <p>
    <%= t('.review_warning_html') %>
  </p>

  <div class="well">
    <h3><%= t '.guidelines' %></h3>
    <ul>
      <% t('.media_guidelines').values.each do |guideline| %>
        <li><%= guideline %></li>
      <% end %>
    </ul>
  </div>

  <%= horizontal_simple_form_for @medium, url: media_path, html: { class: 'are-you-sure' } do |f| %>
    <%= f.input :competitionId, as: :competition_id, only_one: true %>
    <%= f.input :type, include_blank: false %>
    <%= f.input :text %>
    <%= f.input :uri %>
    <%= f.input :submitterComment %>

    <%= f.button :submit %>
  <% end %>
</div>

WcaOnRails/app/views/media/validate.html.erb
<% provide(:title, t('.title')) %>

<div class="container-fluid">
  <%= link_to t('media.common.view_media_page'), media_path %>

  <h2><%= yield(:title) %></h2>

  <%= render "approval_guidelines" %>

  <%= render "media_table", media: @media, show_edit_buttons: true %>
</div>