WcaOnRails/config/routes.rb
    get 'register' => 'registrations#register'
    get 'payment-success' => 'registrations#payment_success'
    get 'register-require-sign-in' => 'registrations#register_require_sign_in'
    resources :competition_tabs, except: [:show], as: :tabs, path: :tabs
    get 'tabs/:id/reorder' => "competition_tabs#reorder", as: :tab_reorder
    # Delegate views and action
    get 'submit-results' => 'results_submission#new', as: :submit_results_edit
    post 'submit-results' => 'results_submission#create', as: :submit_results
    post 'upload-json' => 'results_submission#upload_json', as: :upload_results_json
    # WRT views and action
    get '/admin/upload-results' => "admin#new_results", as: :admin_upload_results_edit
    get '/admin/check-existing-results' => "admin#check_results", as: :admin_check_existing_results
    post '/admin/upload-json' => "admin#create_results", as: :admin_upload_results
    post '/admin/clear-submission' => "admin#clear_results_submission", as: :clear_results_submission
  end
  post 'admin/check-existing-results' => "admin#run_validators", as: :admin_run_validators

  get 'competitions/:competition_id/report/edit' => 'delegate_reports#edit', as: :delegate_report_edit
  get 'competitions/:competition_id/report' => 'delegate_reports#show', as: :delegate_report
  patch 'competitions/:competition_id/report' => 'delegate_reports#update'

  get 'competitions/:id/edit/admin' => 'competitions#admin_edit', as: :admin_edit_competition
  get 'competitions/:id/payment_setup' => 'competitions#payment_setup', as: :competitions_payment_setup
  get 'stripe-connect' => 'competitions#stripe_connect', as: :competitions_stripe_connect
  get 'competitions/:id/events/edit' => 'competitions#edit_events', as: :edit_events
  get 'competitions/:id/schedule/edit' => 'competitions#edit_schedule', as: :edit_schedule
  get 'competitions/edit/nearby_competitions' => 'competitions#nearby_competitions', as: :nearby_competitions
  get 'competitions/edit/time_until_competition' => 'competitions#time_until_competition', as: :time_until_competition
  get 'competitions/:id/edit/clone_competition' => 'competitions#clone_competition', as: :clone_competition
  get 'competitions/edit/currency_convert' => 'competitions#currency_convert', as: :currency_convert

  get 'results/rankings', to: redirect('results/rankings/333/single', status: 302)
  get 'results/rankings/333mbf/average',
      to: redirect(status: 302) { |params, request| URI.parse(request.original_url).query ? "results/rankings/333mbf/single?#{URI.parse(request.original_url).query}" : "results/rankings/333mbf/single" }
  get 'results/rankings/:event_id', to: redirect('results/rankings/%{event_id}/single', status: 302)
  get 'results/rankings/:event_id/:type' => 'results#rankings', as: :rankings
  get 'results/records' => 'results#records', as: :records

  get "media/validate" => 'media#validate', as: :validate_media
  resources :media, only: [:index, :new, :create, :edit, :update, :destroy]

  resources :persons, only: [:index, :show]

  resources :polls, only: [:edit, :new, :vote, :create, :update, :index, :destroy]
  get 'polls/:id/vote' => 'votes#vote', as: 'polls_vote'
  get 'polls/:id/results' => 'polls#results', as: 'polls_results'

  resources :teams, only: [:index, :update, :edit]

  resources :votes, only: [:create, :update]

  post 'competitions/:id/post_announcement' => 'competitions#post_announcement', as: :competition_post_announcement
  post 'competitions/:id/cancel' => 'competitions#cancel_competition', as: :competition_cancel
  post 'competitions/:id/post_results' => 'competitions#post_results', as: :competition_post_results

  get 'panel' => 'panel#index'
  get 'panel/delegate-crash-course', to: redirect('/edudoc/delegate-crash-course/delegate_crash_course.pdf', status: 302)
  patch 'panel/delegate-crash-course' => 'panel#update_delegate_crash_course'
  get 'panel/pending-claims(/:user_id)' => 'panel#pending_claims_for_subordinate_delegates', as: 'pending_claims'
  get 'panel/seniors' => 'panel#seniors'
  resources :notifications, only: [:index]

  root 'posts#homepage'
  resources :posts
  get 'rss' => 'posts#rss'

  post 'upload/image', to: 'upload#image'

  get 'admin/delegates' => 'delegates#stats', as: :delegates_stats

  get 'robots' => 'static_pages#robots'

  get 'server-status' => 'server_status#index'

  get 'translations', to: redirect('translations/status', status: 302)
  get 'translations/status' => 'translations#index'
  get 'translations/edit' => 'translations#edit'
  patch 'translations/update' => 'translations#update'

  get 'about' => 'static_pages#about'
  get 'teams-committees' => 'static_pages#teams_committees'
  get 'documents' => 'static_pages#documents'
  get 'education' => 'static_pages#education'
  get 'delegates' => 'static_pages#delegates'
  get 'disclaimer' => 'static_pages#disclaimer'
  get 'contact' => 'static_pages#contact'
  get 'speedcubing-history' => 'static_pages#speedcubing_history'
  get 'privacy' => 'static_pages#privacy'
  get 'faq' => 'static_pages#faq'
  get 'score-tools' => 'static_pages#score_tools'
  get 'logo' => 'static_pages#logo'
  get 'media-instagram' => 'static_pages#media_instagram'
  get 'wca-workbook-assistant' => 'static_pages#wca_workbook_assistant'
  get 'wca-workbook-assistant-versions' => 'static_pages#wca_workbook_assistant_versions'
  get 'organizer-guidelines' => 'static_pages#organizer_guidelines'
  get 'tutorial' => redirect('/education', status: 302)

  resources :regional_organizations, only: [:new, :update, :edit, :destroy], path: '/regional-organizations'
  get 'organizations' => 'regional_organizations#index'
  get 'admin/regional-organizations' => 'regional_organizations#admin'
  delete 'admin/regional-organizations' => 'regional_organizations#destroy'
  patch 'regional-organizations/:id/edit' => 'regional_organizations#update'
  post 'regional-organizations/new' => 'regional_organizations#create'

  get 'disciplinary' => 'wdc#root'

  get 'contact/website' => 'contacts#website'
  post 'contact/website' => 'contacts#website_create'
  get 'contact/dob' => 'contacts#dob'
  post 'contact/dob' => 'contacts#dob_create'

  get '/regulations' => 'regulations#show', id: 'index'
  get '/regulations/*id' => 'regulations#show'

  get '/admin' => 'admin#index'
  get '/admin/all-voters' => 'admin#all_voters', as: :eligible_voters
  get '/admin/leader-senior-voters' => 'admin#leader_senior_voters', as: :leader_senior_voters
  get '/admin/merge_people' => 'admin#merge_people'
  post '/admin/merge_people' => 'admin#do_merge_people'
  get '/admin/edit_person' => 'admin#edit_person'
  patch '/admin/update_person' => 'admin#update_person'
  get '/admin/person_data' => 'admin#person_data'
  get '/admin/compute_auxiliary_data' => 'admin#compute_auxiliary_data'
  get '/admin/do_compute_auxiliary_data' => 'admin#do_compute_auxiliary_data'
  get '/admin/update_statistics' => 'admin#update_statistics'
  get '/admin/anonymize_person' => 'admin#anonymize_person'
  post '/admin/anonymize_person' => 'admin#do_anonymize_person'
  get '/admin/reassign_wca_id' => 'admin#reassign_wca_id'
  get '/admin/validate_reassign_wca_id' => 'admin#validate_reassign_wca_id'
  post '/admin/reassign_wca_id' => 'admin#do_reassign_wca_id'

  get '/search' => 'search_results#index'

  post '/render_markdown' => 'markdown_renderer#render_markdown'

  patch '/update_locale/:locale' => 'application#update_locale', as: :update_locale

  get '/relations' => 'relations#index'
  get '/relation' => 'relations#relation'

  get '/.well-known/change-password' => redirect('/profile/edit?section=password', status: 302)

  # WFC section
  get '/wfc' => 'wfc#panel'
  scope 'wfc' do
    get '/competitions_export' => 'wfc#competition_export', defaults: { format: :csv }, as: :wfc_competitions_export
    resources :country_bands, only: [:index, :update, :edit], path: '/country-bands'
  end

  scope :archive do
    # NOTE: This is meant for displaying old content of the phpBB forum. It is DEPRECATED!
    resources :forums, only: [:index, :show]
    resources :forum_topics, only: [:show]
  end

  resources :incidents do
    patch '/mark_as/:kind' => 'incidents#mark_as', as: :mark_as
  end

  get '/sso-discourse' => 'users#sso_discourse'

  namespace :api do
    get '/', to: redirect('/api/v0', status: 302)
    namespace :v0 do
      get '/' => 'api#help'
      get '/me' => 'api#me'
      get '/auth/results' => 'api#auth_results'
      get '/export/public' => 'api#export_public'
      get '/scramble-program' => 'api#scramble_program'
      get '/search' => 'api#omni_search'
      get '/search/posts' => 'api#posts_search'
      get '/search/competitions' => 'api#competitions_search'
      get '/search/users' => 'api#users_search'
      get '/search/regulations' => 'api#regulations_search'
      get '/users/:id' => 'api#show_user_by_id', constraints: { id: /\d+/ }
      get '/users/:wca_id' => 'api#show_user_by_wca_id'
      get '/delegates' => 'api#delegates'
      get '/persons' => "persons#index"
      get '/persons/:wca_id' => "persons#show", as: :person
      get '/persons/:wca_id/results' => "persons#results", as: :person_results
      get '/geocoding/search' => 'geocoding#get_location_from_query'
      resources :competitions, only: [:index, :show] do
        get '/wcif' => 'competitions#show_wcif'
        get '/wcif/public' => 'competitions#show_wcif_public'
        get '/results' => 'competitions#results', as: :results
        get '/results/:event_id' => 'competitions#event_results', as: :event_results
        get '/competitors' => 'competitions#competitors'
        get '/registrations' => 'competitions#registrations'
        get '/schedule' => 'competitions#schedule'
        get '/scrambles' => 'competitions#scrambles', as: :scrambles
        get '/scrambles/:event_id' => 'competitions#event_scrambles', as: :event_scrambles
        patch '/wcif' => 'competitions#update_wcif', as: :update_wcif
      end
      get '/records' => "api#records"

WcaOnRails/app/models/incident.rb
# frozen_string_literal: true

class Incident < ApplicationRecord
  has_many :incident_tags, autosave: true, dependent: :destroy
  has_many :incident_competitions, dependent: :destroy
  has_many :competitions, -> { order("Competitions.start_date asc") }, through: :incident_competitions

  accepts_nested_attributes_for :incident_competitions, allow_destroy: true

  scope :resolved, -> { where.not(resolved_at: nil) }

  validate :digest_sent_at_consistent
  validates_presence_of :title

  include Taggable

  def last_happened_date
    competitions.last&.start_date || created_at.to_date
  end

  def digest_missing?
    digest_worthy && !digest_sent_at
  end

  def digest_sent?
    digest_sent_at != nil
  end

  def resolved?
    resolved_at != nil
  end

  def digest_sent_at_consistent
    if digest_sent_at && !digest_worthy
      errors.add(:digest_sent_at, "can't be set if digest_worthy is false.")
    end
    if digest_sent_at && !resolved_at
      errors.add(:digest_sent_at, "can't be set if incident is not resolved.")
    end
  end
end

WcaOnRails/app/controllers/incidents_controller.rb
# frozen_string_literal: true

class IncidentsController < ApplicationController
  include TagsHelper

  # Incident should have a public summary when resolved, so not everything is
  # WRC/Delegates-only.
  before_action -> { authenticate_user! && redirect_to_root_unless_user(:can_manage_incidents?) }, except: [
    :index,
    :show,
  ]

  def index
    base_model = Incident.includes(:competitions, :incident_tags)
    if current_user&.can_view_delegate_matters?
      @incidents = base_model.all
    else
      @incidents = base_model.resolved
    end
    @incidents = @incidents.sort_by(&:last_happened_date).reverse
  end

  def show
    set_incident
    unless @incident.resolved?
      redirect_to_root_unless_user(:can_view_delegate_matters?)
    end
  end

  def new
    @incident = Incident.new
  end

  def edit
    set_incident
  end

  def create
    @incident = Incident.new(incident_params)

    if @incident.save
      flash[:success] = "Incident was successfully created."
      redirect_to @incident
    else
      render :new
    end
  end

  def mark_as
    @incident = Incident.find(params[:incident_id])
    updated_attrs = {}
    case params[:kind]
    when "sent"
      updated_attrs[:digest_sent_at] = Time.now
    when "resolved"
      updated_attrs[:resolved_at] = Time.now
    else
      flash[:danger] = "Unrecognized action: '#{params[:kind]}'"
      return redirect_to @incident
    end

    if @incident.update(updated_attrs)
      flash[:success] = "Successfully updated incident."
    else
      flash[:danger] = "Couldn't mark the incident as sent."
      @incident.errors.each do |key, message|
        flash[:danger] += " #{key} #{message}"
      end
    end
    redirect_to @incident
  end

  def update
    set_incident
    if @incident.update(incident_params)
      flash[:success] = "Incident was successfully updated."
      redirect_to @incident
    else
      render :edit
    end
  end

  def destroy
    set_incident
    if @incident.destroy
      flash[:success] = "Incident was successfully destroyed."
      redirect_to incidents_url
    else
      render :edit
    end
  end

  private

  def set_incident
    @incident = Incident.find(params[:id])
  end

  def incident_params
    params.require(:incident).permit(
      :title,
      :private_description,
      :private_wrc_decision,
      :public_summary,
      :tags,
      :digest_worthy,
      incident_competitions_attributes: [:id, :competition_id, :comments, :_destroy],
    )
  end
end

WcaOnRails/app/helpers/incidents_helper.rb
# frozen_string_literal: true

module IncidentsHelper
  def class_and_text_for_status(incident)
    if incident.resolved_at
      ["success", "Resolved"]
    else
      ["warning", "Pending"]
    end
  end

  def class_and_text_for_digest(incident)
    if incident.digest_worthy
      if incident.digest_sent_at
        ["success", "Sent"]
      else
        ["warning", "Pending"]
      end
    else
      ["success", ""]
    end
  end
end

WcaOnRails/app/views/incidents/_competition_tag.html.erb
<%
comp = incident_competition.competition
data_attributes = ""
link_to_comp = link_to("Competition's page", competition_path(comp), target: "_blank", class: "hide-new-window-icon")
if current_user&.can_view_delegate_matters?
  link_to_report = link_to("Delegate report", delegate_report_path(comp), target: "_blank", class: "hide-new-window-icon")
  content = "#{incident_competition.comments}<hr/>#{link_to_comp}<br/>#{link_to_report}"
else
  content = "#{link_to_comp}"
end
%>
<span tabindex="0" class="competition-tag label label-info" data-toggle="popover" data-placement="bottom" data-trigger="focus" data-html="true" title="<%= comp.name %>" data-content="<%= content %>">
  <%= comp.id %>
</span>

WcaOnRails/app/views/incidents/_form.html.erb
<% add_to_packs("markdown_editor") %>

<%= horizontal_simple_form_for(@incident, html: { class: "incident-form" }) do |f| %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :digest_worthy, disabled: @incident.digest_sent? %>
    <% if @incident.digest_sent? %>
      <div class="form-group"><div class="col-sm-10 col-sm-offset-2">Digest marked as sent on <%= wca_local_time(@incident.digest_sent_at) %></div></div>
    <% end %>
    <%= f.input :private_description, input_html: { class: "markdown-editor" } %>
    <%= f.input :private_wrc_decision, input_html: { class: "markdown-editor" } %>
    <%= f.input :public_summary, input_html: { class: "markdown-editor" } %>
    <hr/>
    <%= f.input :tags %>
    <script>
      $('input#incident_tags').selectize(window.wca.defaultSelectizeOptions(<%= all_to_options(IncidentTag) %>));
    </script>
    <hr/>
    <div class="incident-competitions">
      <%= f.simple_fields_for :incident_competitions do |f2| %>
        <%= render "incident_competition_fields", f: f2 %>
      <% end %>
    </div>
    <div class="row">
      <div class="col-sm-offset-2 col-sm-9">
        <%= link_to_add_association button_tag(raw("#{ui_icon("plus")} Link a competition"), type: "button", class: "btn btn-default"), f, :incident_competitions,
          data: { association_insertion_node: '.incident-competitions', association_insertion_method: 'append' } %>
      </div>
    </div>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn-primary" %>
  </div>
<% end %>

WcaOnRails/app/views/incidents/_incident_competition_fields.html.erb
<div class="nested-fields">
  <%= f.input :competition_id, as: :incident_competition_id, only_one: true, input_html: { class: "competition-selector" }, link_html: link_to_remove_association(button_tag(ui_icon("times"), type: "button", class: "btn btn-danger"), f) %>
  <script>
    $('input.wca-autocomplete').wcaAutocomplete();
  </script>
</div>

WcaOnRails/app/views/incidents/_incident_tag.html.erb
<%
tag ||= ""
js_search ||= false
reg = Regulation.find_or_nil(tag)
label_class = reg ? "primary" : "default"
title = reg ? "#{link_to(reg["id"], reg["url"], target: "_blank")}" : tag
search_tag_link = js_search ? "href='#' onclick='window.wca.searchIncidentsForTag(event, \"#{tag}\");'" : "href='#{incidents_path(tags: tag)}'"
content = "<a #{search_tag_link}>Search incidents with this tag</a>"

if reg
  content = "#{reg["content_html"]} <hr/>" + content
end
%>
<span tabindex="0" class="incident-tag label label-<%= label_class%>" title='<%= title %>' data-toggle="popover" data-placement="bottom" data-content="<%= content %>" data-trigger="focus" data-html="true">
  <%= tag %>
</span>

WcaOnRails/app/views/incidents/_nav.html.erb
<div class="container">
  <% if I18n.locale != I18n.default_locale %>
    <%= alert :info do %>
      <%= t 'incidents_log.i18n_disclaimer' %>
    <% end %>
  <% end %>
  <% unless @incidents %>
    <%= link_to "Back to the incidents log", incidents_path %>
  <% end %>
  <%= yield %>
</div>

WcaOnRails/app/views/incidents/edit.html.erb
<% provide(:title, "Editing incident") %>

<%= render layout: "nav" do %>
  <h1><%= yield(:title) %></h1>

  <%= render 'form', incident: @incident %>
<% end %>

WcaOnRails/app/views/incidents/index.html.erb
<% provide(:title, "Incidents log") %>

<%= render layout: "nav" do %>
  <h1><%= yield(:title) %></h1>

  <div id="custom-search-toolbar">
    <input id="incident-tags" class="form-control" type="text" placeholder="Filter by tags">
  </div>
  <div class="incidents-log-table-container">
    <%= wca_table(table_class: "incidents-log-table", data: { toggle: "table", pagination: true, search: true, toolbar: "#custom-search-toolbar" }, floatThead: false, greedy: false) do %>
      <thead>
        <tr>
          <th>Title</th>
          <th class="tags-cell">Tags</th>
          <th class="comps-cell" data-field="happened" data-sortable="true" data-sorter="incidentsSorter">Happened during</th>
          <th class="status-cell">Status</th>
          <% if current_user&.can_view_delegate_matters? %>
            <th class="digest-cell" data-field="digest-sent" data-sortable="true">Sent in digest</th>
          <% end %>
        </tr>
      </thead>

      <tbody>
        <% @incidents.each do |incident| %>
          <tr>
            <td><%= link_to incident.title, incident %></td>
            <td data-tags="<%= incident.tags %>">
              <% incident.tags_array.each do |t| %>
                <%= render "incident_tag", tag: t, js_search: true %>
              <% end %>
            </td>
            <td data-competitions="<%= incident.competitions %>">
              <div data-last-happened="<%= incident.last_happened_date %>">
                <% incident.incident_competitions.each do |incident_competition| %>
                  <%= render "competition_tag", incident_competition: incident_competition %>
                <% end %>
              </div>
            </td>
            <% status_class, status_text = class_and_text_for_status(incident) %>
            <td class="text-<%= status_class %>"><%= status_text %></td>
            <% if current_user&.can_view_delegate_matters? %>
              <% digest_class, digest_text = class_and_text_for_digest(incident) %>
              <td class="text-<%= digest_class %>"><%= digest_text %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    <% end %>
  </div>

  <script>
    function incidentsSorter(a, b) {
      dateA = $(a).data("last-happened");
      dateB = $(b).data("last-happened");
      if (dateA < dateB) {
        return -1;
      } else if (dateA > dateB) {
        return 1;
      } else {
        return 0;
      }
    }
    $(function() {
      var opts = window.wca.defaultSelectizeOptions(<%= all_to_options(IncidentTag) %>);
      window.wca.initIncidentsLogTable(opts, $('.incidents-log-table'), '.search input', $('input#incident-tags'));
    });
  </script>

  <br>
  <% if current_user&.can_manage_incidents? %>
    <%= link_to new_incident_path, class: "btn btn-success" do %>
      <%= ui_icon('plus') %> New Incident
    <% end %>
  <% end %>

<% end %>

WcaOnRails/app/views/incidents/new.html.erb
<% provide(:title, "Create a new incident") %>

<%= render layout: "nav" do %>
  <h1><%= yield(:title) %></h1>

  <%= render 'form', incident: @incident %>
<% end %>

WcaOnRails/app/views/incidents/show.html.erb
<% provide(:title, "Incident: #{@incident.title}") %>

<%= render layout: "nav" do %>
  <h1><%= yield(:title) %></h1>

  <div>
    <strong>Status:</strong>
    <% if @incident.resolved_at %>
      <span class="text-success">Resolved</span>
    <% else %>
      <span class="text-warning">Pending</span>
    <% end %>
  </div>

  <p>
    <% @incident.tags_array.each do |t| %>
      <%= render "incident_tag", tag: t %>
    <% end %>
  </p>
  <p>
    <% @incident.incident_competitions.each do |incident_competition| %>
      <%= render "competition_tag", incident_competition: incident_competition %>
    <% end %>
  </p>
  <% warning_text = "" %>
  <% unless @incident.resolved_at %>
    <% warning_text += "This incident is pending, a final ruling and public description may not be available.<br/>" %>
  <% end %>
  <% if current_user&.can_manage_incidents? %>
    <% if @incident.digest_missing? %>
      <% warning_text += "This incident should be sent in a digest" %>
      <% unless @incident.resolved_at %>
        <% warning_text += " after being resolved" %>
      <% end %>
      <% warning_text += ".<br/>" %>
    <% end %>
  <% end %>
  <% unless warning_text.blank? %>
    <%= alert :warning do %>
      <%= raw(warning_text) %>
    <% end %>
  <% end %>

  <div>
    <strong>Incident description and resolution:</strong>
    <%=md @incident.public_summary %>
  </div>

  <% if current_user&.can_view_delegate_matters? %>
    <div>
      <strong>Description (private to Delegates):</strong>
      <%=md @incident.private_description %>
    </div>
  <% end %>

  <% if current_user&.can_view_incident_private_sections?(@incident) %>
    <div>
      <strong>WRC Decision (private to Delegates):</strong>
      <%=md @incident.private_wrc_decision %>
    </div>
  <% end %>

  <% if current_user&.can_manage_incidents? %>
    <% if @incident.digest_missing? && @incident.resolved_at %>
      <%= link_to 'Sent in a digest', incident_mark_as_path(@incident.id, "sent"), class: "btn btn-success", method: :patch, data: { confirm: "You are about to mark this incident as sent in a digest, are you sure?" } %>
    <% end %>
    <% unless @incident.resolved_at %>
      <%= link_to 'Mark as resolved', incident_mark_as_path(@incident.id, "resolved"), class: "btn btn-success", method: :patch, data: { confirm: "You are about to mark this incident as resolved, are you sure?" } %>
    <% end %>
    <%= link_to 'Edit', edit_incident_path(@incident), class: "btn btn-primary" %>
    <%= link_to 'Destroy', incident_path(@incident), class: "btn btn-danger", method: :delete, data: { confirm: "Are you sure you want to delete this incident?" } %>
  <% end %>

  <hr/>
  <div>
    This incident was created on <%= wca_local_time(@incident.created_at) %>.
  </div>
  <% if @incident.digest_sent? %>
    <div>
      This incident was marked as sent to Delegates in a WRC digest on <%= wca_local_time(@incident.digest_sent_at) %>.
    </div>
  <% end %>
<% end %>