WcaOnRails/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  use_doorkeeper do
    controllers applications: 'oauth/applications'
  end

  # Starburst announcements, see https://github.com/starburstgem/starburst#installation
  mount Starburst::Engine => '/starburst'

  # Prevent account deletion, and overrides the sessions controller for 2FA.
  #  https://github.com/plataformatec/devise/wiki/How-To:-Disable-user-from-destroying-their-account
  devise_for :users, skip: :registrations, controllers: { sessions: "sessions" }
  devise_scope :user do
    resource :registration,
             only: [:new, :create],
             path: 'users',
             path_names: { new: 'sign_up' },
             controller: 'accounts/registrations',
             as: :user_registration do
               get :cancel
             end
    post 'users/generate-email-otp' => 'sessions#generate_email_otp'
    post 'users/authenticate-sensitive' => 'users#authenticate_user_for_sensitive_edit'
    delete 'users/sign-out-other' => 'sessions#destroy_other', as: :destroy_other_user_sessions
  end
  post 'registration/:id/refund/:payment_id' => 'registrations#refund_payment', as: :registration_payment_refund
  post 'registration/:id/process-payment-intent' => 'registrations#process_payment_intent', as: :registration_payment_intent
  resources :users, only: [:index, :edit, :update]
  get 'profile/edit' => 'users#edit'
  post 'profile/enable-2fa' => 'users#enable_2fa'
  post 'profile/disable-2fa' => 'users#disable_2fa'
  post 'profile/generate-2fa-backup' => 'users#regenerate_2fa_backup_codes'
  post 'profile/acknowledge-cookies' => 'users#acknowledge_cookies'

  get 'profile/claim_wca_id' => 'users#claim_wca_id'
  get 'profile/claim_wca_id/select_nearby_delegate' => 'users#select_nearby_delegate'

  get 'users/:id/edit/avatar_thumbnail' => 'users#edit_avatar_thumbnail', as: :users_avatar_thumbnail_edit
  get 'users/:id/edit/pending_avatar_thumbnail' => 'users#edit_pending_avatar_thumbnail', as: :users_pending_avatar_thumbnail_edit
  get 'admin/avatars' => 'admin/avatars#index'
  post 'admin/avatars' => 'admin/avatars#update_all'

  get 'map' => 'competitions#embedable_map'

  get 'competitions/mine' => 'competitions#my_competitions', as: :my_comps
  get 'competitions/for_senior(/:user_id)' => 'competitions#for_senior', as: :competitions_for_senior
  post 'competitions/bookmark' => 'competitions#bookmark', as: :bookmark
  post 'competitions/unbookmark' => 'competitions#unbookmark', as: :unbookmark

  resources :competitions, only: [:index, :show, :edit, :update, :new, :create] do
    get 'results/podiums' => 'competitions#show_podiums'
    get 'results/all' => 'competitions#show_all_results'
    get 'results/by_person' => 'competitions#show_results_by_person'
    get 'scrambles' => 'competitions#show_scrambles'

    patch 'registrations/selected' => 'registrations#do_actions_for_selected', as: :registrations_do_actions_for_selected
    post 'registrations/export' => 'registrations#export', as: :registrations_export
    get 'registrations/import' => 'registrations#import', as: :registrations_import
    post 'registrations/import' => 'registrations#do_import', as: :registrations_do_import
    get 'registrations/add' => 'registrations#add', as: :registrations_add
    post 'registrations/add' => 'registrations#do_add', as: :registrations_do_add
    get 'registrations/psych-sheet' => 'registrations#psych_sheet', as: :psych_sheet
    get 'registrations/psych-sheet/:event_id' => 'registrations#psych_sheet_event', as: :psych_sheet_event
    resources :registrations, only: [:index, :update, :create, :edit, :destroy], shallow: true
    get 'edit/registrations' => 'registrations#edit_registrations'
    get 'register' => 'registrations#register'
    get 'payment-success' => 'registrations#payment_success'
    get 'register-require-sign-in' => 'registrations#register_require_sign_in'
    resources :competition_tabs, except: [:show], as: :tabs, path: :tabs
    get 'tabs/:id/reorder' => "competition_tabs#reorder", as: :tab_reorder
    # Delegate views and action
    get 'submit-results' => 'results_submission#new', as: :submit_results_edit
    post 'submit-results' => 'results_submission#create', as: :submit_results
    post 'upload-json' => 'results_submission#upload_json', as: :upload_results_json
    # WRT views and action
    get '/admin/upload-results' => "admin#new_results", as: :admin_upload_results_edit
    get '/admin/check-existing-results' => "admin#check_results", as: :admin_check_existing_results
    post '/admin/upload-json' => "admin#create_results", as: :admin_upload_results
    post '/admin/clear-submission' => "admin#clear_results_submission", as: :clear_results_submission
  end
  post 'admin/check-existing-results' => "admin#run_validators", as: :admin_run_validators

  get 'competitions/:competition_id/report/edit' => 'delegate_reports#edit', as: :delegate_report_edit
  get 'competitions/:competition_id/report' => 'delegate_reports#show', as: :delegate_report
  patch 'competitions/:competition_id/report' => 'delegate_reports#update'

  get 'competitions/:id/edit/admin' => 'competitions#admin_edit', as: :admin_edit_competition
  get 'competitions/:id/payment_setup' => 'competitions#payment_setup', as: :competitions_payment_setup
  get 'stripe-connect' => 'competitions#stripe_connect', as: :competitions_stripe_connect
  get 'competitions/:id/events/edit' => 'competitions#edit_events', as: :edit_events
  get 'competitions/:id/schedule/edit' => 'competitions#edit_schedule', as: :edit_schedule
  get 'competitions/edit/nearby_competitions' => 'competitions#nearby_competitions', as: :nearby_competitions
  get 'competitions/edit/time_until_competition' => 'competitions#time_until_competition', as: :time_until_competition
  get 'competitions/:id/edit/clone_competition' => 'competitions#clone_competition', as: :clone_competition
  get 'competitions/edit/currency_convert' => 'competitions#currency_convert', as: :currency_convert

  get 'results/rankings', to: redirect('results/rankings/333/single', status: 302)
  get 'results/rankings/333mbf/average',
      to: redirect(status: 302) { |params, request| URI.parse(request.original_url).query ? "results/rankings/333mbf/single?#{URI.parse(request.original_url).query}" : "results/rankings/333mbf/single" }
  get 'results/rankings/:event_id', to: redirect('results/rankings/%{event_id}/single', status: 302)
  get 'results/rankings/:event_id/:type' => 'results#rankings', as: :rankings
  get 'results/records' => 'results#records', as: :records

  get "media/validate" => 'media#validate', as: :validate_media
  resources :media, only: [:index, :new, :create, :edit, :update, :destroy]

  resources :persons, only: [:index, :show]

  resources :polls, only: [:edit, :new, :vote, :create, :update, :index, :destroy]
  get 'polls/:id/vote' => 'votes#vote', as: 'polls_vote'
  get 'polls/:id/results' => 'polls#results', as: 'polls_results'

  resources :teams, only: [:index, :update, :edit]

  resources :votes, only: [:create, :update]

  post 'competitions/:id/post_announcement' => 'competitions#post_announcement', as: :competition_post_announcement
  post 'competitions/:id/cancel' => 'competitions#cancel_competition', as: :competition_cancel
  post 'competitions/:id/post_results' => 'competitions#post_results', as: :competition_post_results

  get 'panel' => 'panel#index'
  get 'panel/delegate-crash-course', to: redirect('/edudoc/delegate-crash-course/delegate_crash_course.pdf', status: 302)
  patch 'panel/delegate-crash-course' => 'panel#update_delegate_crash_course'
  get 'panel/pending-claims(/:user_id)' => 'panel#pending_claims_for_subordinate_delegates', as: 'pending_claims'
  get 'panel/seniors' => 'panel#seniors'
  resources :notifications, only: [:index]

  root 'posts#homepage'
  resources :posts
  get 'rss' => 'posts#rss'

  post 'upload/image', to: 'upload#image'

  get 'admin/delegates' => 'delegates#stats', as: :delegates_stats

  get 'robots' => 'static_pages#robots'

  get 'server-status' => 'server_status#index'

  get 'translations', to: redirect('translations/status', status: 302)
  get 'translations/status' => 'translations#index'
  get 'translations/edit' => 'translations#edit'
  patch 'translations/update' => 'translations#update'

  get 'about' => 'static_pages#about'
  get 'teams-committees' => 'static_pages#teams_committees'
  get 'documents' => 'static_pages#documents'
  get 'education' => 'static_pages#education'
  get 'delegates' => 'static_pages#delegates'
  get 'disclaimer' => 'static_pages#disclaimer'
  get 'contact' => 'static_pages#contact'
  get 'speedcubing-history' => 'static_pages#speedcubing_history'
  get 'privacy' => 'static_pages#privacy'
  get 'faq' => 'static_pages#faq'
  get 'score-tools' => 'static_pages#score_tools'
  get 'logo' => 'static_pages#logo'
  get 'media-instagram' => 'static_pages#media_instagram'
  get 'wca-workbook-assistant' => 'static_pages#wca_workbook_assistant'
  get 'wca-workbook-assistant-versions' => 'static_pages#wca_workbook_assistant_versions'
  get 'organizer-guidelines' => 'static_pages#organizer_guidelines'
  get 'tutorial' => redirect('/education', status: 302)

  resources :regional_organizations, only: [:new, :update, :edit, :destroy], path: '/regional-organizations'
  get 'organizations' => 'regional_organizations#index'
  get 'admin/regional-organizations' => 'regional_organizations#admin'
  delete 'admin/regional-organizations' => 'regional_organizations#destroy'
  patch 'regional-organizations/:id/edit' => 'regional_organizations#update'
  post 'regional-organizations/new' => 'regional_organizations#create'

  get 'disciplinary' => 'wdc#root'

  get 'contact/website' => 'contacts#website'
  post 'contact/website' => 'contacts#website_create'
  get 'contact/dob' => 'contacts#dob'
  post 'contact/dob' => 'contacts#dob_create'

  get '/regulations' => 'regulations#show', id: 'index'
  get '/regulations/*id' => 'regulations#show'

WcaOnRails/app/models/format.rb
# frozen_string_literal: true

class Format < ApplicationRecord
  include Cachable
  self.table_name = "Formats"

  has_many :preferred_formats
  has_many :events, through: :preferred_formats

  scope :recommended, -> { where("ranking = 1") }

  def name
    I18n.t("formats.#{id}", default: self[:name])
  end

  def short_name
    I18n.t("formats.short.#{id}", default: self[:name])
  end

  def allowed_first_phase_formats
    {
      "1" => [],
      "2" => ["1"],
      "3" => ["1", "2"],
      "m" => ["1", "2"],
      "a" => ["2"], # https://www.worldcubeassociation.org/regulations/#9b1
    }[self.id]
  end

  def serializable_hash(options = nil)
    {
      id: self.id,
      name: self.name,
      sort_by: self.sort_by,
      sort_by_second: self.sort_by_second,
      expected_solve_count: self.expected_solve_count,
      trim_fastest_n: self.trim_fastest_n,
      trim_slowest_n: self.trim_slowest_n,
      allowed_first_phase_formats: self.allowed_first_phase_formats,
    }
  end
end

WcaOnRails/app/controllers/api/v0/competitions_controller.rb
# frozen_string_literal: true

class Api::V0::CompetitionsController < Api::V0::ApiController
  # Enable CSRF protection if we use cookies based user instead of OAuth one.
  protect_from_forgery if: -> { current_user.present? }, with: :exception

  def index
    managed_by_user = nil
    if params[:managed_by_me].present?
      require_scope!("manage_competitions")
      managed_by_user = current_api_user || current_user
    end

    competitions = Competition.search(params[:q], params: params, managed_by_user: managed_by_user)
    competitions = competitions.includes(:delegates, :organizers, :events)

    paginate json: competitions
  end

  def show
    competition = competition_from_params
    render json: competition
  end

  def schedule
    competition = competition_from_params
    render json: competition.schedule_wcif
  end

  def results
    competition = competition_from_params
    render json: competition.results
  end

  def event_results
    competition = competition_from_params
    event = Event.c_find!(params[:event_id])
    results_by_round = competition.results
                                  .where(eventId: event.id)
                                  .group_by(&:round_type)
                                  .sort_by { |round_type, _| -round_type.rank }
    rounds = results_by_round.map do |round_type, results|
      {
        id: round_type.id,
        # Also include the (localized) name here, we don't have i18n in js yet.
        name: round_type.name,
        results: results.sort_by { |r| [r.pos, r.personName] },
      }
    end
    render json: {
      id: event.id,
      # Also include the (localized) name here, we don't have i18n in js yet.
      name: event.name,
      rounds: rounds,
    }
  end

  def scrambles
    competition = competition_from_params
    render json: competition.scrambles
  end

  def event_scrambles
    competition = competition_from_params
    event = Event.c_find!(params[:event_id])
    scrambles_by_round = competition.scrambles
                                    .where(eventId: event.id)
                                    .group_by(&:round_type)
                                    .sort_by { |round_type, _| -round_type.rank }
    rounds = scrambles_by_round.map do |round_type, scrambles|
      {
        id: round_type,
        # Also include the (localized) name here, we don't have i18n in js yet.
        name: round_type.name,
        scrambles: scrambles,
      }
    end
    render json: {
      id: event.id,
      # Also include the (localized) name here, we don't have i18n in js yet.
      name: event.name,
      rounds: rounds,
    }
  end

  def competitors
    competition = competition_from_params
    render json: competition.competitors
  end

  def registrations
    competition = competition_from_params
    render json: competition.registrations.accepted.includes(:events)
  end

  def show_wcif
    competition = competition_from_params
    require_can_manage!(competition)

    render json: competition.to_wcif(authorized: true)
  end

  def show_wcif_public
    competition = competition_from_params

    cache_key = "wcif/#{competition.id}"
    render json: Rails.cache.fetch(cache_key, expires_in: 5.minutes) {
      competition.to_wcif
    }
  end

  def update_wcif
    competition = competition_from_params
    require_can_manage!(competition)
    wcif = params.permit!.to_h
    wcif = wcif["_json"] || wcif
    competition.set_wcif!(wcif, require_user!)
    render json: {
      status: "Successfully saved WCIF",
    }
  rescue ActiveRecord::RecordInvalid => e
    render status: 400, json: {
      status: "Error while saving WCIF",
      error: e,
    }
  rescue JSON::Schema::ValidationError => e
    render status: 400, json: {
      status: "Error while saving WCIF",
      error: e.message,
    }
  end

  private def competition_from_params
    id = params[:competition_id] || params[:id]
    competition = Competition.find_by_id(id)

    # If this competition exists, but is not publicly visible, then only show it
    # to the user if they are able to manage the competition.
    if competition && !competition.showAtAll && !can_manage?(competition)
      competition = nil
    end

    raise WcaExceptions::NotFound.new("Competition with id #{id} not found") unless competition
    competition
  end

  private def can_manage?(competition)
    api_user_can_manage = current_api_user&.can_manage_competition?(competition) && doorkeeper_token.scopes.exists?("manage_competitions")
    api_user_can_manage || current_user&.can_manage_competition?(competition)
  end

  private def require_user!
    raise WcaExceptions::MustLogIn.new if current_api_user.nil? && current_user.nil?
    current_api_user || current_user
  end

  private def require_scope!(scope)
    require_user!
    if current_api_user # If we deal with an OAuth user then check the scopes.
      raise WcaExceptions::BadApiParameter.new("Missing required scope '#{scope}'") unless doorkeeper_token.scopes.include?(scope)
    end
  end

  def require_can_manage!(competition)
    require_user!
    raise WcaExceptions::NotPermitted.new("Not authorized to manage competition") unless can_manage?(competition)
  end
end

WcaOnRails/app/views/competitions/_index_table.html.erb
<ul class="list-group">
  <li class="list-group-item"><strong><%= "#{title} (#{competitions.count})" %></strong></li>
  <% competitions.each_with_index do |competition, index| %>
    <% if index > 0 && competition.year != competitions[index - 1].year && params[:event_ids].empty? %>
      <li class="list-group-item break"><%= competition.year %></li>
    <% end %>
    <% li_classes = ["list-group-item"] %>
    <% li_classes << (competition.is_probably_over? ? "past" : "not-past") %>
    <% li_classes << "cancelled" if competition.cancelled? %>
    <li class="<%= li_classes.join(' ') %>">
      <span class="date">
        <% if competition.is_probably_over? %>
          <% if competition.results_posted? %>
            <%= ui_icon('check circle', title: t('competitions.index.tooltips.hourglass.posted'), class: "results-posted-indicator", data: { toggle: "tooltip" }) %>
          <% else %>
            <%= ui_icon('hourglass end', title: t('competitions.index.tooltips.hourglass.ended', days: t('common.days', count:(Date.today - competition.end_date).to_i)), data: { toggle: "tooltip" }) %>
          <% end %>
        <% elsif competition.in_progress? %>
          <%= ui_icon('hourglass half', title: t('competitions.index.tooltips.hourglass.in_progress'), data: { toggle: "tooltip" }) %>
        <% elsif @by_announcement_selected %>
          <%= ui_icon('hourglass start', title: t('competitions.index.tooltips.hourglass.announced_on', announcement_date: competition.announced_at.strftime(" %F %H:%M:%S")), data: { toggle: "tooltip" }) %>
        <% else %>
          <%= ui_icon('hourglass start', title: t('competitions.index.tooltips.hourglass.starts_in', days: t('common.days', count:(competition.start_date - Date.today).to_i)), data: { toggle: "tooltip" }) %>
        <% end %>
        <%= wca_date_range(competition.start_date, competition.end_date) %>
      </span>
      <span class="competition-info">
        <div class="competition-link">
          <%= flag_icon competition.country.iso2 %>
          <%= link_to competition.display_name(short: true), competition_path(competition) %>
        </div>
        <div class="location">
          <strong><%= competition.country.name %></strong>, <%= competition.cityName %>
        </div>
        <div class="venue-link">
          <%=md(competition.venue, target_blank: true) %>
        </div>
      </span>
    </li>
  <% end %>
</ul>

<script>
  <%# Tooltips have to be initialized manually after each Ajax response in order to work. %>
  $('[data-toggle="tooltip"]').tooltip();
</script>

WcaOnRails/app/views/competitions/_my_competitions_table.html.erb
<% show_delegates ||= false %>
<% bookmarked ||= false %>
<% registrations_by_competition_id ||= {} %>
<% if competitions.length < 1 %>
  <%= alert :info do %>
    <% if bookmarked %>
      <%= t '.no_bookmarked_competitions' %>
    <% elsif !past %>
      <%= t '.no_upcoming_competitions_html', link: link_to(t('.competitions_list'), competitions_path) %>
    <% else %>
      <%= t '.no_past_competitions' %>
    <% end %>
  <% end %>
<% else %>
  <div class="table-responsive">
    <table class="table competitions-table floatThead <%= past ? "table-striped" : "" %>">
      <thead>
        <tr>
          <th><%= t 'competitions.nearby_competitions.name' %></th>
          <th><%= t 'competitions.nearby_competitions.location' %></th>
          <th><%= t 'competitions.nearby_competitions.date' %></th>
          <th></th>
          <th></th>
          <th></th>
          <th><%= "Delegates" if show_delegates %></th>
          <th class="big-column"></th>
        </tr>
      </thead>
      <tbody>
        <% competitions.each do |competition| %>
          <% registration = registrations_by_competition_id[competition.id] %>
          <% tr_classes = [ competition.confirmed? ? "confirmed" : "not-confirmed",
                          competition.showAtAll? ? "visible" : "not-visible",
                          competition.cancelled? ? "cancelled" : "",
                          past ? "past" : "not-past" ].join(' ') %>
          <tr class="<%= tr_classes %>"
              data-toggle="tooltip" data-placement="bottom" data-container="body"
              title="<%= competition_message_for_user(competition, current_user) unless past %>">
            <td>
              <%= link_to competition.display_name, competition_path(competition) %>
              <% if competition.championships.any? %>
                <span class="championship-trophy" data-toggle="tooltip" data-placement="bottom" title="<%= competition.championships.sort.map { |championship| championship.name }.join(", ") %>">
                  <%= ui_icon('trophy') %>
                </span>
              <% end %>
            </td>
            <td><%= competition.city_and_country %></td>
            <td><%= wca_date_range(competition.start_date, competition.end_date) %></td>
            <td>
              <% if registration %>
                <%= ui_icon(registration.accepted? ? "calendar check" : "hourglass half") %>
              <% end %>
            </td>
            <td>
              <% if !past && current_user.can_manage_competition?(competition) %>
                <%= link_to t('.edit'), edit_competition_path(competition) %>
              <% elsif competition.results_posted? %>
                <%= ui_icon("check circle", data: { toggle: "tooltip", placement: "top", container: "body" }, title: t('.results_up')) %>
              <% end %>
            </td>
            <td>
              <% if !past && competition.use_wca_registration? && current_user.can_manage_competition?(competition) %>
                <%= link_to t('.registrations'), competition_edit_registrations_path(competition) %>
              <% end %>
            </td>
            <td>
              <% if show_delegates %>
                <%= competition.delegates.map(&:name).join(", ") %>
              <% else %>
                <% if current_user.can_view_delegate_report?(competition.delegate_report) %>
                  <%= link_to ui_icon('file alt'), delegate_report_path(competition), title: t('.report'), data: { 'toggle': 'tooltip', 'container': 'body' } %>
                <% end %>
                <% if current_user.can_edit_delegate_report?(competition.delegate_report) %>
                  <%= link_to ui_icon('edit'), delegate_report_edit_path(competition), title: t('.edit_report'), data: { 'toggle': 'tooltip', 'container': 'body' } %>
                <% end %>
                <% if competition.user_should_post_delegate_report?(current_user) %>
                  <%= ui_icon('warning', title: t('.missing_report'), data: { 'toggle': 'tooltip', 'container': 'body' }) %>
                <% end %>
              <% end %>
            </td>
            <td class="big-column"></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

WcaOnRails/app/views/competitions/_nearby_competitions_table.html.erb
<table class="table">
  <tr>
    <td><%= t 'competitions.nearby_competitions.name' %></td>
    <td><%= t 'competitions.nearby_competitions.delegates' %></td>
    <td><%= t 'competitions.nearby_competitions.date' %></td>
    <td><%= t 'competitions.nearby_competitions.location' %></td>
    <td><%= t 'competitions.nearby_competitions.distance' %></td>
    <td><%= t 'competitions.nearby_competitions.limit' %></td>
    <td><%= t 'competitions.nearby_competitions.competitors' %></td>
    <td class="wca-nearby-competitions-show-events"><%= t 'competitions.nearby_competitions.events' %></td>
  </tr>
  <% nearby_competitions.each do |c| %>
    <tr class="<%= @competition.dangerously_close_to?(c) ? "danger" : "warning" %>">
      <td class="text-nowrap">
        <%= if current_user.can_admin_results?
          link_to c.name, admin_edit_competition_path(c.id), target: "_blank"
        else
          link_to c.name, competition_path(c.id)
        end %>
        <% unless c.confirmed? %>
          <i class="fas fa-exclamation-circle" data-toggle="tooltip" data-placement="top" data-container="body" title="This competition is not confirmed yet."></i>
        <% end %>
      </td>
      <td><%= users_to_sentence c.delegates %></td>
      <% days_until = @competition.days_until_competition?(c) %>
      <% tooltipTitle = c.name + " " + (days_until < 0 ? t('competitions.nearby_competitions.ends_on') + " " + c.end_date.to_s : t('competitions.nearby_competitions.starts_on') + " " + c.start_date.to_s) %>
      <td data-toggle="tooltip" data-placement="top" data-container="body" title="<%= tooltipTitle %>">
      <%=t('datetime.distance_in_words.x_days', count: days_until.abs) %> <%= days_until < 0 ? t('competitions.nearby_competitions.before') : t('competitions.nearby_competitions.after') %>
      </td>
      <td><%= c.cityName %>, <%= c.countryId %></td>
      <td class="text-nowrap text-right">
        <%= link_to_google_maps_dir "#{@competition.kilometers_to(c).round(2)} km", c.latitude_degrees, c.longitude_degrees, @competition.latitude_degrees, @competition.longitude_degrees %>
      </td>
      <td class="text-center"><%= c.competitor_limit if c.competitor_limit_enabled %></td>
      <td class="text-center"><%= c.competitors.count if c.is_probably_over? %></td>
      <td class="wca-nearby-competitions-show-events">
        <% c.events.each do |event| %>
          <%= cubing_icon event.id, data: { toggle: "tooltip", placement: "bottom", container: "body" }, title: event.name %>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

WcaOnRails/app/views/competitions/_results_table.html.erb
<% hide_event = defined?(hide_event) && hide_event %>
<% hide_round = defined?(hide_round) && hide_round %>
<% hide_pos = defined?(hide_pos) && hide_pos %>
<% hide_name = defined?(hide_name) && hide_name %>

<%= wca_table table_class: "wca-results", floatThead: false do %>
  <thead>
    <tr>
      <% if !hide_event %>
        <th class="event"><%= t '.event' %></th>
      <% end %>

      <% if !hide_round %>
        <th class="round"><%= t '.round' %></th>
      <% end %>

      <% if !hide_pos %>
        <th class="pos">#</th>
      <% end %>

      <% if !hide_name %>
        <th class="name"><%= t '.name' %></th>
      <% end %>

      <th class="single"><%= t 'common.best' %></th>
      <th class="regionalSingleRecord"></th>

      <th class="average"><%= t 'common.average' %></th>
      <th class="regionalSingleRecord"></th>

      <th class="country"><%= t 'common.user.citizen_of' %></th>
      <th class="solves" colspan="5"><%= t 'common.solves' %></th>

      <% # Extra column for .table-greedy-last-column %>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% results.each_with_index do |result, i| %>
      <tr class="sort-by-<%= result.format.sort_by.to_s %> <%= result.muted ? "text-muted" : "" %>">
        <% if !hide_event %>
          <td class="event">
            <% if !result.muted && (i == 0 || result.eventId != results[i - 1].eventId) %>
              <%= link_to competition_results_all_path(@competition, event: result.eventId) do %>
                <%= cubing_icon result.event.id %>
                <%= result.event.name %>
              <% end %>
            <% end %>
          </td>
        <% end %>

        <% if !hide_round %>
          <td class="round"><%= result.round_type.cellName %></td>
        <% end %>

        <% if !hide_pos %>
          <% classes = "pos" %>
          <% previous_result = i > 0 ? results[i - 1] : nil %>
          <% if previous_result && previous_result.eventId == result.eventId && previous_result.roundTypeId == result.roundTypeId && previous_result.pos == result.pos %>
            <% classes << " tied-previous" %>
          <% end %>
          <td class="<%= classes %>">
            <%= result.pos %>
          </td>
        <% end %>

        <% if !hide_name %>
          <td class="name">
            <% if result.wca_id %>
              <%= link_to result.personName, person_path(result.wca_id) %>
            <% else %>
              <%= result.personName %>
            <% end %>
          </td>
        <% end %>

        <td class="single"><%= result.best_solve.clock_format %></td>
        <td class="regionalSingleRecord"><%= result.regionalSingleRecord %></td>

        <td class="average"><%= result.average_solve.clock_format %></td>
        <td class="regionalAverageRecord"><%= result.regionalAverageRecord %></td>

        <td class="country"><%= result.country.name %></td>

        <%= solve_tds_for_result(result) %>

        <% # Extra column for .table-greedy-last-column %>
        <td></td>
      </tr>
    <% end %>
  </tbody>
<% end %>